package com.mads.hiber;
// Generated Jan 27, 2021 8:25:22 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", catalog = "hibernate_db")
public class Profile implements java.io.Serializable {

	private int profileId;
	private String firstname;
	private String lastname;
	private String email;
	private String phone;
	private Double cctc;
	private Integer nperiod;

	public Profile() {
	}

	public Profile(int profileId) {
		this.profileId = profileId;
	}

	public Profile(int profileId, String firstname, String lastname, String email, String phone, Double cctc,
			Integer nperiod) {
		this.profileId = profileId;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.phone = phone;
		this.cctc = cctc;
		this.nperiod = nperiod;
	}

	@Id

	@Column(name = "profileID", unique = true, nullable = false)
	public int getProfileId() {
		return this.profileId;
	}

	public void setProfileId(int profileId) {
		this.profileId = profileId;
	}

	@Column(name = "firstname", length = 15)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", length = 15)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "cctc", precision = 22, scale = 0)
	public Double getCctc() {
		return this.cctc;
	}

	public void setCctc(Double cctc) {
		this.cctc = cctc;
	}

	@Column(name = "nperiod")
	public Integer getNperiod() {
		return this.nperiod;
	}

	public void setNperiod(Integer nperiod) {
		this.nperiod = nperiod;
	}

}
