package com.mads.hiber;
// Generated Jan 27, 2021 8:25:22 AM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", catalog = "hibernate_db")
public class Student implements java.io.Serializable {

	private Integer studId;
	private String studName;
	private String studAddress;
	private String studContact;
	private String studEmail;

	public Student() {
	}

	public Student(String studName, String studAddress, String studContact, String studEmail) {
		this.studName = studName;
		this.studAddress = studAddress;
		this.studContact = studContact;
		this.studEmail = studEmail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "stud_id", unique = true, nullable = false)
	public Integer getStudId() {
		return this.studId;
	}

	public void setStudId(Integer studId) {
		this.studId = studId;
	}

	@Column(name = "stud_name", nullable = false, length = 45)
	public String getStudName() {
		return this.studName;
	}

	public void setStudName(String studName) {
		this.studName = studName;
	}

	@Column(name = "stud_address", nullable = false, length = 45)
	public String getStudAddress() {
		return this.studAddress;
	}

	public void setStudAddress(String studAddress) {
		this.studAddress = studAddress;
	}

	@Column(name = "stud_contact", nullable = false, length = 45)
	public String getStudContact() {
		return this.studContact;
	}

	public void setStudContact(String studContact) {
		this.studContact = studContact;
	}

	@Column(name = "stud_email", nullable = false, length = 45)
	public String getStudEmail() {
		return this.studEmail;
	}

	public void setStudEmail(String studEmail) {
		this.studEmail = studEmail;
	}

}
